name: pull-request

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: recursive

      - name: Build amd64
        id: test-amd64
        run: |
          podman build .

  arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: recursive

      - name: Install qemu-user-static
        id: install-qemu
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt install -y qemu-user-static

      - name: Build arm64
        id: test-arm64
        run: |
          podman build -f Dockerfile.arm64

